/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <ApplicationCode.h>
#include <Scheduler.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//volatile uint32_t flag = 0;

void EXTI0_IRQHandler() {
	// disable further interrupts while processing
	IRQ_disable(EXTI0_IRQ_NUMBER);
	toggleGreenLED();
//	flag=0xfcc0;
//	syncButton();
//	appDelay(DELAY_MAG);
//	if (EXTI->PR & (1<<0)) {
	// Clear the pending interrupt
	IRQ_exti_line_clear(UBUT_PIN);
	IRQ_clear(EXTI0_IRQ_NUMBER);
//	}
	IRQ_enable(EXTI0_IRQ_NUMBER);

}

int main(void)
{
	applicationInit();
	uint32_t eventsToRun;
    /* Loop forever */
	for(;;) {
		eventsToRun = getScheduledEvents();
		if ((eventsToRun & LED_TOGGLE_EVENT) != 0) {
			toggleGreenLED();
//			toggleRedLED();
		}
		if ((eventsToRun & DELAY_EVENT) != 0) {
			appDelay(DELAY_MAG);
		}
		if ((eventsToRun & POLL_BTN_EVENT) != 0) {
			syncButton();
		}
	}
}
