/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE and Modified by Peter Hindes
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "./ApplicationCode.h"

#define DELAY_BETWEEN_BLINKS 25000

//#define GPIOG_RCC_ENABLE_ADDRESS 0x40023830 // RCC_AHB1ENR register file contains the enable bits for the gpio group clocks
//#define GPIOG_AHB1ENR_BIT_OFFSET 6 // bit 6 of that register enables gpio group g
//#define GPIOG_MODER_ADDRESS 0x40021800
//#define GPIOG_ODR_ADDRESS 0x40021814
//
//#define RED_LED_MODER_BIT_OFFSET 28
//#define RED_LED_OUT_MODE_BIT_VALUES 0b01 //General purpose output mode
//#define RED_LED_ODR_BIT_OFFSET 14
//
//#define LEN_OF_NAME 5 //peter

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	EnablePeripheralsAndClocks();
	TurnOffRedLED(); // Ensure that the value is initialized to zero
    /* Loop forever */
	for(;;) {
		ToggleRedLED();
		AppDelay(DELAY_BETWEEN_BLINKS);
	}
}
